services:
  adonis:
    image: node:20.6.0
    container_name: shopper-measures
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3333
      - DB_CONNECTION=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_DATABASE=measure_shopper
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    command: >
      sh -c "npm install && node ace migration:run && npm run dev"

  postgres:
    image: postgres:15
    container_name: adonis_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=measure_shopper
    ports:
      - '5432:5432'

volumes:
  postgres_data:
